# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e54f89e6775fa590a73303fecd0641b75a223b11a9def1b7fe0ccb36c585a8e7fc9967d81f431b98697b88590009d1cd29bf0fb2dbedb62890e4379f51b0396

test:
  secret_key_base: 1933c9479d15b1e5ba89d468730962902debd0bc60c58dd484790d1ce11d2bc9516a93eeb4031cb0a167260112e3882c09baaffea055aeb21f3ce39645da29df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
